// <auto-generated />
using System;
using ClassLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(LeMarconnesDbContext))]
    partial class LeMarconnesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccommodationReservation", b =>
                {
                    b.Property<int>("AccommodationsAccommodationId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("AccommodationsAccommodationId", "ReservationId");

                    b.HasIndex("ReservationId");

                    b.ToTable("AccommodationReservation");
                });

            modelBuilder.Entity("ClassLibrary.Models.Accommodation", b =>
                {
                    b.Property<int>("AccommodationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccommodationId"));

                    b.Property<int>("AccommodationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("PlaceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccommodationId");

                    b.HasIndex("AccommodationTypeId");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            AccommodationId = 1,
                            AccommodationTypeId = 1,
                            Capacity = 4,
                            PlaceNumber = "1A"
                        },
                        new
                        {
                            AccommodationId = 2,
                            AccommodationTypeId = 1,
                            Capacity = 4,
                            PlaceNumber = "2A"
                        },
                        new
                        {
                            AccommodationId = 3,
                            AccommodationTypeId = 1,
                            Capacity = 4,
                            PlaceNumber = "3A"
                        },
                        new
                        {
                            AccommodationId = 4,
                            AccommodationTypeId = 1,
                            Capacity = 4,
                            PlaceNumber = "4A"
                        },
                        new
                        {
                            AccommodationId = 5,
                            AccommodationTypeId = 1,
                            Capacity = 4,
                            PlaceNumber = "5A"
                        },
                        new
                        {
                            AccommodationId = 6,
                            AccommodationTypeId = 2,
                            Capacity = 1,
                            PlaceNumber = "101"
                        },
                        new
                        {
                            AccommodationId = 7,
                            AccommodationTypeId = 2,
                            Capacity = 2,
                            PlaceNumber = "201"
                        },
                        new
                        {
                            AccommodationId = 8,
                            AccommodationTypeId = 2,
                            Capacity = 2,
                            PlaceNumber = "202"
                        },
                        new
                        {
                            AccommodationId = 9,
                            AccommodationTypeId = 2,
                            Capacity = 3,
                            PlaceNumber = "301"
                        },
                        new
                        {
                            AccommodationId = 10,
                            AccommodationTypeId = 2,
                            Capacity = 4,
                            PlaceNumber = "304"
                        },
                        new
                        {
                            AccommodationId = 11,
                            AccommodationTypeId = 2,
                            Capacity = 5,
                            PlaceNumber = "307"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Models.AccommodationType", b =>
                {
                    b.Property<int>("AccommodationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccommodationTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccommodationTypeId");

                    b.ToTable("AccommodationTypes");

                    b.HasData(
                        new
                        {
                            AccommodationTypeId = 1,
                            TypeName = "Camping"
                        },
                        new
                        {
                            AccommodationTypeId = 2,
                            TypeName = "Hotel"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountRole = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAED40poWknsiW1HtrueqpONicGpEl+0PpLBHkmcd2Pia8jyo2ZarTY7CqSz8gfUyPLQ==",
                            RegistrationDate = new DateTime(2026, 1, 20, 15, 40, 40, 120, DateTimeKind.Local).AddTicks(8949),
                            Username = "Admin"
                        },
                        new
                        {
                            AccountId = 3,
                            AccountRole = "Employee",
                            PasswordHash = "AQAAAAIAAYagAAAAEJkbsW3FiATzLlh0GWtFksdZjlDSF6B4FCQvRoSbI9k2kSYzKDnSHFrYKNkhsTxKqw==",
                            RegistrationDate = new DateTime(2026, 1, 20, 15, 40, 40, 120, DateTimeKind.Local).AddTicks(8999),
                            Username = "Employee"
                        },
                        new
                        {
                            AccountId = 2,
                            AccountRole = "Customer",
                            CustomerId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEJkbsW3FiATzLlh0GWtFksdZjlDSF6B4FCQvRoSbI9k2kSYzKDnSHFrYKNkhsTxKqw==",
                            RegistrationDate = new DateTime(2026, 1, 20, 15, 40, 40, 120, DateTimeKind.Local).AddTicks(9009),
                            Username = "Customer"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "test.customer@gmail.com",
                            FirstName = "Test",
                            LastName = "Customer",
                            Phone = "0612345678",
                            RegistrationDate = new DateTime(2026, 1, 20, 15, 40, 40, 120, DateTimeKind.Local).AddTicks(9025)
                        });
                });

            modelBuilder.Entity("ClassLibrary.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reservations");

                    b.HasDiscriminator<string>("ReservationType").HasValue("Reservation");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ClassLibrary.Models.Tariff", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffId"));

                    b.Property<int>("AccommodationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("TariffId");

                    b.HasIndex("AccommodationTypeId");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            TariffId = 1,
                            AccommodationTypeId = 1,
                            Name = "Campingplaats",
                            Price = 7.50m
                        },
                        new
                        {
                            TariffId = 2,
                            AccommodationTypeId = 1,
                            Name = "Volwassene",
                            Price = 6.00m
                        },
                        new
                        {
                            TariffId = 3,
                            AccommodationTypeId = 1,
                            Name = "Kind_0_7",
                            Price = 4.00m
                        },
                        new
                        {
                            TariffId = 4,
                            AccommodationTypeId = 1,
                            Name = "Kind_7_12",
                            Price = 5.00m
                        },
                        new
                        {
                            TariffId = 5,
                            AccommodationTypeId = 1,
                            Name = "Hond",
                            Price = 2.50m
                        },
                        new
                        {
                            TariffId = 6,
                            AccommodationTypeId = 1,
                            Name = "Electriciteit",
                            Price = 7.50m
                        },
                        new
                        {
                            TariffId = 7,
                            AccommodationTypeId = 1,
                            Name = "Toeristenbelasting",
                            Price = 0.25m
                        },
                        new
                        {
                            TariffId = 8,
                            AccommodationTypeId = 2,
                            Name = "Hotelkamer_1Persoon",
                            Price = 42.50m
                        },
                        new
                        {
                            TariffId = 9,
                            AccommodationTypeId = 2,
                            Name = "Hotelkamer_2Personen",
                            Price = 55.00m
                        },
                        new
                        {
                            TariffId = 10,
                            AccommodationTypeId = 2,
                            Name = "Hotelkamer_3Personen",
                            Price = 70.00m
                        },
                        new
                        {
                            TariffId = 11,
                            AccommodationTypeId = 2,
                            Name = "Hotelkamer_4personen",
                            Price = 88.00m
                        },
                        new
                        {
                            TariffId = 12,
                            AccommodationTypeId = 2,
                            Name = "Hotelkamer_5personen",
                            Price = 105.50m
                        },
                        new
                        {
                            TariffId = 13,
                            AccommodationTypeId = 2,
                            Name = "Toeristenbelasting",
                            Price = 0.50m
                        });
                });

            modelBuilder.Entity("CampingReservation", b =>
                {
                    b.HasBaseType("ClassLibrary.Models.Reservation");

                    b.Property<int>("AdultsCount")
                        .HasColumnType("int");

                    b.Property<int>("Children0_7Count")
                        .HasColumnType("int");

                    b.Property<int>("Children7_12Count")
                        .HasColumnType("int");

                    b.Property<int>("DogsCount")
                        .HasColumnType("int");

                    b.Property<int?>("ElectricityDays")
                        .HasColumnType("int");

                    b.Property<bool>("HasElectricity")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Camping");
                });

            modelBuilder.Entity("HotelReservation", b =>
                {
                    b.HasBaseType("ClassLibrary.Models.Reservation");

                    b.Property<int>("PersonCount")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Hotel");
                });

            modelBuilder.Entity("AccommodationReservation", b =>
                {
                    b.HasOne("ClassLibrary.Models.Accommodation", null)
                        .WithMany()
                        .HasForeignKey("AccommodationsAccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassLibrary.Models.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassLibrary.Models.Accommodation", b =>
                {
                    b.HasOne("ClassLibrary.Models.AccommodationType", "AccommodationType")
                        .WithMany()
                        .HasForeignKey("AccommodationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccommodationType");
                });

            modelBuilder.Entity("ClassLibrary.Models.Account", b =>
                {
                    b.HasOne("ClassLibrary.Models.Customer", "Customer")
                        .WithOne()
                        .HasForeignKey("ClassLibrary.Models.Account", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClassLibrary.Models.Reservation", b =>
                {
                    b.HasOne("ClassLibrary.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClassLibrary.Models.Tariff", b =>
                {
                    b.HasOne("ClassLibrary.Models.AccommodationType", "AccommodationType")
                        .WithMany()
                        .HasForeignKey("AccommodationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccommodationType");
                });
#pragma warning restore 612, 618
        }
    }
}
