// <auto-generated />
using System;
using ClassLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary.Migrations
{
    [DbContext(typeof(CampingDbContext))]
    [Migration("20260105021315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccommodationReservation", b =>
                {
                    b.Property<int>("AccommodationsAccommodationId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationsReservationId")
                        .HasColumnType("int");

                    b.HasKey("AccommodationsAccommodationId", "ReservationsReservationId");

                    b.HasIndex("ReservationsReservationId");

                    b.ToTable("AccommodationReservation");
                });

            modelBuilder.Entity("ClassLibrary.Models.Accommodation", b =>
                {
                    b.Property<int>("AccommodationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccommodationId"));

                    b.Property<int>("AccommodationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PlaceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccommodationId");

                    b.HasIndex("AccommodationTypeId");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            AccommodationId = 1,
                            AccommodationTypeId = 1,
                            Capacity = 10,
                            CurrentStatus = "Beschikbaar",
                            PlaceNumber = "1A"
                        },
                        new
                        {
                            AccommodationId = 2,
                            AccommodationTypeId = 1,
                            Capacity = 10,
                            CurrentStatus = "Beschikbaar",
                            PlaceNumber = "2A"
                        },
                        new
                        {
                            AccommodationId = 3,
                            AccommodationTypeId = 1,
                            Capacity = 10,
                            CurrentStatus = "Beschikbaar",
                            PlaceNumber = "3A"
                        },
                        new
                        {
                            AccommodationId = 4,
                            AccommodationTypeId = 1,
                            Capacity = 10,
                            CurrentStatus = "Beschikbaar",
                            PlaceNumber = "4A"
                        },
                        new
                        {
                            AccommodationId = 5,
                            AccommodationTypeId = 1,
                            Capacity = 10,
                            CurrentStatus = "Beschikbaar",
                            PlaceNumber = "5A"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Models.AccommodationType", b =>
                {
                    b.Property<int>("AccommodationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccommodationTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccommodationTypeId");

                    b.ToTable("AccommodationsTypes");

                    b.HasData(
                        new
                        {
                            AccommodationTypeId = 1,
                            Name = "Camping"
                        },
                        new
                        {
                            AccommodationTypeId = 2,
                            Name = "Hotel"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<int>("AccountRole")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ClassLibrary.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ClassLibrary.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("AdultsCount")
                        .HasColumnType("int");

                    b.Property<int>("Children0_7Count")
                        .HasColumnType("int");

                    b.Property<int>("Children7_12Count")
                        .HasColumnType("int");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DogsCount")
                        .HasColumnType("int");

                    b.Property<int?>("ElectricityDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasElectricity")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasCheckConstraint("CHK_EndAfterStart", "EndDate > StartDate");

                            t.HasCheckConstraint("CHK_ValidCounts", "AdultsCount >= 1");
                        });
                });

            modelBuilder.Entity("ClassLibrary.Models.Tariff", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffId"));

                    b.Property<int>("AccommodationTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TariffId");

                    b.HasIndex("AccommodationTypeId");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            TariffId = 1,
                            AccommodationTypeId = 1,
                            Price = 7.50m,
                            Type = "Campingplaats"
                        },
                        new
                        {
                            TariffId = 2,
                            AccommodationTypeId = 1,
                            Price = 6.00m,
                            Type = "Volwassene"
                        },
                        new
                        {
                            TariffId = 3,
                            AccommodationTypeId = 1,
                            Price = 4.00m,
                            Type = "Kind_0_7"
                        },
                        new
                        {
                            TariffId = 4,
                            AccommodationTypeId = 1,
                            Price = 5.00m,
                            Type = "Kind_7_12"
                        },
                        new
                        {
                            TariffId = 5,
                            AccommodationTypeId = 1,
                            Price = 2.50m,
                            Type = "Hond"
                        },
                        new
                        {
                            TariffId = 6,
                            AccommodationTypeId = 1,
                            Price = 7.50m,
                            Type = "Electriciteit"
                        },
                        new
                        {
                            TariffId = 7,
                            AccommodationTypeId = 1,
                            Price = 0.25m,
                            Type = "Toeristenbelasting"
                        });
                });

            modelBuilder.Entity("AccommodationReservation", b =>
                {
                    b.HasOne("ClassLibrary.Models.Accommodation", null)
                        .WithMany()
                        .HasForeignKey("AccommodationsAccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassLibrary.Models.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationsReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassLibrary.Models.Accommodation", b =>
                {
                    b.HasOne("ClassLibrary.Models.AccommodationType", "AccommodationType")
                        .WithMany("Accommodations")
                        .HasForeignKey("AccommodationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccommodationType");
                });

            modelBuilder.Entity("ClassLibrary.Models.Account", b =>
                {
                    b.HasOne("ClassLibrary.Models.Customer", "Customer")
                        .WithOne()
                        .HasForeignKey("ClassLibrary.Models.Account", "CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClassLibrary.Models.Reservation", b =>
                {
                    b.HasOne("ClassLibrary.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClassLibrary.Models.Tariff", b =>
                {
                    b.HasOne("ClassLibrary.Models.AccommodationType", "AccommodationType")
                        .WithMany("Tariffs")
                        .HasForeignKey("AccommodationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccommodationType");
                });

            modelBuilder.Entity("ClassLibrary.Models.AccommodationType", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Tariffs");
                });

            modelBuilder.Entity("ClassLibrary.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
