// <auto-generated />
using System;
using ClassLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary.Migrations
{
    [DbContext(typeof(LeMarconnesDbContext))]
    partial class LeMarconnesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccommodationReservation", b =>
                {
                    b.Property<int>("AccommodationsAccommodationId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationsReservationId")
                        .HasColumnType("int");

                    b.HasKey("AccommodationsAccommodationId", "ReservationsReservationId");

                    b.HasIndex("ReservationsReservationId");

                    b.ToTable("AccommodationReservation");
                });

            modelBuilder.Entity("ClassLibrary.Models.Accommodation", b =>
                {
                    b.Property<int>("AccommodationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccommodationId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("PlaceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("AccommodationId");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            AccommodationId = 1,
                            Capacity = 4,
                            PlaceNumber = "1A",
                            Type = 1
                        },
                        new
                        {
                            AccommodationId = 2,
                            Capacity = 4,
                            PlaceNumber = "2A",
                            Type = 1
                        },
                        new
                        {
                            AccommodationId = 3,
                            Capacity = 4,
                            PlaceNumber = "3A",
                            Type = 1
                        },
                        new
                        {
                            AccommodationId = 4,
                            Capacity = 4,
                            PlaceNumber = "4A",
                            Type = 1
                        },
                        new
                        {
                            AccommodationId = 5,
                            Capacity = 4,
                            PlaceNumber = "5A",
                            Type = 1
                        },
                        new
                        {
                            AccommodationId = 6,
                            Capacity = 1,
                            PlaceNumber = "101",
                            Type = 2
                        },
                        new
                        {
                            AccommodationId = 7,
                            Capacity = 2,
                            PlaceNumber = "201",
                            Type = 2
                        },
                        new
                        {
                            AccommodationId = 8,
                            Capacity = 2,
                            PlaceNumber = "202",
                            Type = 2
                        },
                        new
                        {
                            AccommodationId = 9,
                            Capacity = 3,
                            PlaceNumber = "301",
                            Type = 2
                        },
                        new
                        {
                            AccommodationId = 10,
                            Capacity = 4,
                            PlaceNumber = "304",
                            Type = 2
                        },
                        new
                        {
                            AccommodationId = 11,
                            Capacity = 5,
                            PlaceNumber = "307",
                            Type = 2
                        });
                });

            modelBuilder.Entity("ClassLibrary.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ClassLibrary.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ClassLibrary.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("AccommodationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reservations");

                    b.HasDiscriminator<string>("ReservationType").HasValue("Reservation");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ClassLibrary.Models.Tariff", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffId"));

                    b.Property<int>("AccommodationType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("TariffId");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            TariffId = 1,
                            AccommodationType = 1,
                            Name = "Campingplaats",
                            Price = 7.50m
                        },
                        new
                        {
                            TariffId = 2,
                            AccommodationType = 1,
                            Name = "Volwassene",
                            Price = 6.00m
                        },
                        new
                        {
                            TariffId = 3,
                            AccommodationType = 1,
                            Name = "Kind_0_7",
                            Price = 4.00m
                        },
                        new
                        {
                            TariffId = 4,
                            AccommodationType = 1,
                            Name = "Kind_7_12",
                            Price = 5.00m
                        },
                        new
                        {
                            TariffId = 5,
                            AccommodationType = 1,
                            Name = "Hond",
                            Price = 2.50m
                        },
                        new
                        {
                            TariffId = 6,
                            AccommodationType = 1,
                            Name = "Electriciteit",
                            Price = 7.50m
                        },
                        new
                        {
                            TariffId = 7,
                            AccommodationType = 1,
                            Name = "Toeristenbelasting",
                            Price = 0.25m
                        },
                        new
                        {
                            TariffId = 8,
                            AccommodationType = 2,
                            Name = "Hotelkamer_1Persoon",
                            Price = 42.50m
                        },
                        new
                        {
                            TariffId = 9,
                            AccommodationType = 2,
                            Name = "Hotelkamer_2Personen",
                            Price = 55.00m
                        },
                        new
                        {
                            TariffId = 10,
                            AccommodationType = 2,
                            Name = "Hotelkamer_3Personen",
                            Price = 70.00m
                        },
                        new
                        {
                            TariffId = 11,
                            AccommodationType = 2,
                            Name = "Hotelkamer_4personen",
                            Price = 88.00m
                        },
                        new
                        {
                            TariffId = 12,
                            AccommodationType = 2,
                            Name = "Hotelkamer_5personen",
                            Price = 105.50m
                        },
                        new
                        {
                            TariffId = 13,
                            AccommodationType = 2,
                            Name = "Toeristenbelasting",
                            Price = 0.50m
                        });
                });

            modelBuilder.Entity("CampingReservation", b =>
                {
                    b.HasBaseType("ClassLibrary.Models.Reservation");

                    b.Property<int>("AdultsCount")
                        .HasColumnType("int");

                    b.Property<int>("Children0_7Count")
                        .HasColumnType("int");

                    b.Property<int>("Children7_12Count")
                        .HasColumnType("int");

                    b.Property<int>("DogsCount")
                        .HasColumnType("int");

                    b.Property<int?>("ElectricityDays")
                        .HasColumnType("int");

                    b.Property<bool>("HasElectricity")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Camping");
                });

            modelBuilder.Entity("HotelReservation", b =>
                {
                    b.HasBaseType("ClassLibrary.Models.Reservation");

                    b.Property<int>("PersonCount")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Hotel");
                });

            modelBuilder.Entity("AccommodationReservation", b =>
                {
                    b.HasOne("ClassLibrary.Models.Accommodation", null)
                        .WithMany()
                        .HasForeignKey("AccommodationsAccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassLibrary.Models.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationsReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassLibrary.Models.Account", b =>
                {
                    b.HasOne("ClassLibrary.Models.Customer", "Customer")
                        .WithOne()
                        .HasForeignKey("ClassLibrary.Models.Account", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClassLibrary.Models.Reservation", b =>
                {
                    b.HasOne("ClassLibrary.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClassLibrary.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
